import { Exercise } from "@/types";

// Additional exercises to expand the library from 25 to 50+ exercises
// Categorized by equipment preference: machines, free weights, bodyweight, cables

export const ADDITIONAL_EXERCISES: Exercise[] = [
  // CHEST - Machine variations
  {
    id: "chest-press-machine",
    name: "Chest Press Machine",
    muscleGroup: "chest",
    equipment: ["machine"],
    gifUrl: "/exercises/chest-press-machine.gif",
    description:
      "Machine-based chest press, great for beginners and isolation.",
    tips: [
      "Adjust seat height so handles align with mid-chest",
      "Keep back flat against pad",
      "Full range of motion",
    ],
    alternatives: ["bench-press", "incline-dumbbell-press"],
  },
  {
    id: "pec-deck",
    name: "Pec Deck Fly",
    muscleGroup: "chest",
    equipment: ["machine"],
    gifUrl: "/exercises/pec-deck.gif",
    description: "Isolation exercise for chest, machine-guided movement.",
    tips: ["Slight bend in elbows", "Squeeze at center", "Control the stretch"],
    alternatives: ["cable-fly", "push-ups"],
  },
  {
    id: "dumbbell-fly",
    name: "Dumbbell Chest Fly",
    muscleGroup: "chest",
    equipment: ["dumbbell"],
    gifUrl: "/exercises/dumbbell-fly.gif",
    description: "Free weight chest isolation with dumbbells.",
    tips: [
      "Slight bend in elbows throughout",
      "Arc motion, not straight up",
      "Feel the stretch at bottom",
    ],
    alternatives: ["cable-fly", "pec-deck"],
  },

  // BACK - Machine variations
  {
    id: "seated-row-machine",
    name: "Seated Cable Row",
    muscleGroup: "back",
    equipment: ["machine", "cable"],
    gifUrl: "/exercises/seated-row-machine.gif",
    description: "Machine-based rowing for mid-back thickness.",
    tips: [
      "Keep chest up",
      "Pull to lower sternum",
      "Squeeze shoulder blades together",
    ],
    alternatives: ["barbell-row", "dumbbell-row"],
  },
  {
    id: "t-bar-row",
    name: "T-Bar Row",
    muscleGroup: "back",
    equipment: ["barbell", "machine"],
    gifUrl: "/exercises/t-bar-row.gif",
    description: "Powerful rowing variation for back thickness.",
    tips: ["Chest on pad if using machine", "Pull to lower chest", "Elbows in"],
    alternatives: ["barbell-row", "seated-row-machine"],
  },
  {
    id: "pullover",
    name: "Dumbbell Pullover",
    muscleGroup: "back",
    equipment: ["dumbbell"],
    gifUrl: "/exercises/pullover.gif",
    description: "Targets lats and chest with stretching motion.",
    tips: [
      "Lie perpendicular on bench",
      "Keep hips low",
      "Stretch arms behind head",
    ],
    alternatives: ["lat-pulldown", "cable-fly"],
  },

  // LEGS - Machine variations
  {
    id: "leg-extension",
    name: "Leg Extension",
    muscleGroup: "legs",
    equipment: ["machine"],
    gifUrl: "/exercises/leg-extension.gif",
    description: "Isolation exercise for quadriceps.",
    tips: [
      "Align knee with machine pivot",
      "Controlled movement",
      "Squeeze at top",
    ],
    alternatives: ["barbell-squat", "leg-press"],
  },
  {
    id: "hack-squat",
    name: "Hack Squat Machine",
    muscleGroup: "legs",
    equipment: ["machine"],
    gifUrl: "/exercises/hack-squat.gif",
    description: "Machine squat variation, great for quad development.",
    tips: ["Feet shoulder-width apart", "Knees track over toes", "Full depth"],
    alternatives: ["barbell-squat", "leg-press"],
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    muscleGroup: "legs",
    equipment: ["dumbbell", "bodyweight"],
    gifUrl: "/exercises/bulgarian-split-squat.gif",
    description: "Single-leg exercise for balance and leg development.",
    tips: [
      "Rear foot elevated on bench",
      "Torso upright",
      "Front knee stays behind toes",
    ],
    alternatives: ["lunges", "barbell-squat"],
  },
  {
    id: "calf-raise",
    name: "Standing Calf Raise",
    muscleGroup: "legs",
    equipment: ["machine", "dumbbell"],
    gifUrl: "/exercises/calf-raise.gif",
    description: "Isolation for calf muscles.",
    tips: ["Full range of motion", "Pause at top", "Stretch at bottom"],
    alternatives: ["seated-calf-raise"],
  },
  {
    id: "seated-calf-raise",
    name: "Seated Calf Raise",
    muscleGroup: "legs",
    equipment: ["machine"],
    gifUrl: "/exercises/seated-calf-raise.gif",
    description: "Targets soleus muscle in calves.",
    tips: ["Knees bent at 90 degrees", "Full stretch", "Controlled reps"],
    alternatives: ["calf-raise"],
  },

  // SHOULDERS - More variations
  {
    id: "arnold-press",
    name: "Arnold Press",
    muscleGroup: "shoulders",
    equipment: ["dumbbell"],
    gifUrl: "/exercises/arnold-press.gif",
    description: "Rotating dumbbell press for complete shoulder development.",
    tips: [
      "Start with palms facing you",
      "Rotate as you press",
      "Full range of motion",
    ],
    alternatives: ["overhead-press", "lateral-raise"],
  },
  {
    id: "shoulder-press-machine",
    name: "Shoulder Press Machine",
    muscleGroup: "shoulders",
    equipment: ["machine"],
    gifUrl: "/exercises/shoulder-press-machine.gif",
    description: "Machine-based shoulder press for stability.",
    tips: ["Adjust seat height", "Press straight up", "Full extension"],
    alternatives: ["overhead-press", "arnold-press"],
  },
  {
    id: "rear-delt-fly",
    name: "Rear Delt Fly",
    muscleGroup: "shoulders",
    equipment: ["dumbbell", "machine"],
    gifUrl: "/exercises/rear-delt-fly.gif",
    description: "Isolation for rear deltoids.",
    tips: ["Bend forward", "Arms slightly bent", "Squeeze shoulder blades"],
    alternatives: ["face-pull"],
  },
  {
    id: "upright-row",
    name: "Upright Row",
    muscleGroup: "shoulders",
    equipment: ["barbell", "dumbbell"],
    gifUrl: "/exercises/upright-row.gif",
    description: "Compound movement for shoulders and traps.",
    tips: ["Pull elbows high", "Keep bar close to body", "Don't go too heavy"],
    alternatives: ["lateral-raise", "overhead-press"],
  },

  // ARMS - Biceps variations
  {
    id: "preacher-curl",
    name: "Preacher Curl",
    muscleGroup: "biceps",
    equipment: ["barbell", "dumbbell", "machine"],
    gifUrl: "/exercises/preacher-curl.gif",
    description: "Isolation curl with arm support for strict form.",
    tips: ["Arms fully extended at bottom", "No swinging", "Squeeze at top"],
    alternatives: ["barbell-curl", "hammer-curl"],
  },
  {
    id: "concentration-curl",
    name: "Concentration Curl",
    muscleGroup: "biceps",
    equipment: ["dumbbell"],
    gifUrl: "/exercises/concentration-curl.gif",
    description: "Single-arm isolation for bicep peak.",
    tips: ["Elbow against inner thigh", "Full contraction", "Slow tempo"],
    alternatives: ["hammer-curl", "barbell-curl"],
  },
  {
    id: "cable-curl",
    name: "Cable Bicep Curl",
    muscleGroup: "biceps",
    equipment: ["cable"],
    gifUrl: "/exercises/cable-curl.gif",
    description: "Constant tension cable variation for biceps.",
    tips: ["Elbows at sides", "Full range", "Control the negative"],
    alternatives: ["barbell-curl", "preacher-curl"],
  },

  // ARMS - Triceps variations
  {
    id: "skull-crusher",
    name: "Skull Crusher (Lying Tricep Extension)",
    muscleGroup: "triceps",
    equipment: ["barbell", "dumbbell"],
    gifUrl: "/exercises/skull-crusher.gif",
    description: "Lying tricep extension for mass building.",
    tips: [
      "Lower to forehead or behind head",
      "Elbows stationary",
      "Full extension",
    ],
    alternatives: ["tricep-extension", "close-grip-bench"],
  },
  {
    id: "tricep-pushdown",
    name: "Tricep Pushdown",
    muscleGroup: "triceps",
    equipment: ["cable"],
    gifUrl: "/exercises/tricep-pushdown.gif",
    description: "Cable isolation for triceps.",
    tips: ["Elbows at sides", "Full extension", "Control the return"],
    alternatives: ["tricep-dips", "tricep-extension"],
  },
  {
    id: "diamond-pushups",
    name: "Diamond Push-Ups",
    muscleGroup: "triceps",
    equipment: ["bodyweight"],
    gifUrl: "/exercises/diamond-pushups.gif",
    description: "Bodyweight exercise emphasizing triceps.",
    tips: [
      "Hands form diamond shape",
      "Elbows close to body",
      "Full range of motion",
    ],
    alternatives: ["tricep-dips", "close-grip-bench"],
  },

  // CORE - More variations
  {
    id: "ab-crunch-machine",
    name: "Ab Crunch Machine",
    muscleGroup: "core",
    equipment: ["machine"],
    gifUrl: "/exercises/ab-crunch-machine.gif",
    description: "Machine-based ab work with added resistance.",
    tips: ["Exhale on crunch", "Full contraction", "Controlled return"],
    alternatives: ["cable-crunch", "plank"],
  },
  {
    id: "russian-twist",
    name: "Russian Twist",
    muscleGroup: "core",
    equipment: ["bodyweight", "dumbbell"],
    gifUrl: "/exercises/russian-twist.gif",
    description: "Rotational core exercise for obliques.",
    tips: ["Lean back slightly", "Touch floor each side", "Keep core tight"],
    alternatives: ["cable-crunch", "plank"],
  },
  {
    id: "bicycle-crunches",
    name: "Bicycle Crunches",
    muscleGroup: "core",
    equipment: ["bodyweight"],
    gifUrl: "/exercises/bicycle-crunches.gif",
    description: "Dynamic ab exercise with rotation.",
    tips: ["Elbow to opposite knee", "Extend other leg", "Controlled tempo"],
    alternatives: ["russian-twist", "hanging-leg-raise"],
  },
  {
    id: "mountain-climbers",
    name: "Mountain Climbers",
    muscleGroup: "core",
    equipment: ["bodyweight"],
    gifUrl: "/exercises/mountain-climbers.gif",
    description: "Dynamic core and cardio exercise.",
    tips: ["Plank position", "Drive knees to chest", "Quick pace"],
    alternatives: ["plank", "bicycle-crunches"],
  },
];
